// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCk6ZHm8Lu56TxFTcZzJFaetN5AZwES2d8',
    appId: '1:895892805290:web:fcd7230d5f7e9d725262d3',
    messagingSenderId: '895892805290',
    projectId: 'travel-buddy-cc014',
    authDomain: 'travel-buddy-cc014.firebaseapp.com',
    storageBucket: 'travel-buddy-cc014.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDe8MstDWmI-7zigrQUT5j0fTaMZgYQJqE',
    appId: '1:895892805290:android:00f7067a89f364a25262d3',
    messagingSenderId: '895892805290',
    projectId: 'travel-buddy-cc014',
    storageBucket: 'travel-buddy-cc014.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbsCd_4BFbD0SBptPnk6_WG9XZjlXMr40',
    appId: '1:895892805290:ios:ab320daed4a90f545262d3',
    messagingSenderId: '895892805290',
    projectId: 'travel-buddy-cc014',
    storageBucket: 'travel-buddy-cc014.firebasestorage.app',
    iosBundleId: 'com.example.travelBuddyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbsCd_4BFbD0SBptPnk6_WG9XZjlXMr40',
    appId: '1:895892805290:ios:ab320daed4a90f545262d3',
    messagingSenderId: '895892805290',
    projectId: 'travel-buddy-cc014',
    storageBucket: 'travel-buddy-cc014.firebasestorage.app',
    iosBundleId: 'com.example.travelBuddyApp',
  );
}
